# Compiler
CC = gcc

# Options de compilation
CFLAGS = -Wall -g `sdl2-config --cflags` -I/usr/include/SDL2 -I/usr/include/SDL2_gfx

# Options de liaison
LDFLAGS = `sdl2-config --libs` -lSDL2_gfx -lm

# Nom de l'exécutable
TARGET = my_sdl_program

# Dossier pour les fichiers objets et l'exécutable
BUILDDIR = build

# Fichiers sources
SRC = main.c

# Fichiers objets
OBJ = $(BUILDDIR)/main.o

# README
README = ../README.md

# Règle par défaut
all: $(BUILDDIR) $(BUILDDIR)/$(TARGET)

# Créer le dossier build si nécessaire
$(BUILDDIR):
	mkdir -p $(BUILDDIR)

# Lien des objets
$(BUILDDIR)/$(TARGET): $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

# Compilation des fichiers sources
$(BUILDDIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Nettoyage
clean:
	rm -rf $(BUILDDIR)

# Exécuter le programme
run: $(BUILDDIR)/$(TARGET) readme
	./$(BUILDDIR)/$(TARGET)

# Afficher le README
readme:
	cat $(README)
