# Compiler
CC = gcc

# Options de compilation (avec les options spécifiques à SDL2 via sdl2-config)
CFLAGS = -Wall -g `sdl2-config --cflags`

# Options de liaison (pour lier les bibliothèques SDL2)
LDFLAGS = `sdl2-config --libs`

# Nom de l'exécutable
TARGET = my_sdl_program

# Dossier pour les fichiers objets et l'exécutable
BUILDDIR = build

# Fichiers sources
SRC = main.c

# Fichiers objets (dans le dossier build)
OBJ = $(BUILDDIR)/main.o

# Règle par défaut : compilation complète
all: $(BUILDDIR) $(BUILDDIR)/$(TARGET)

# Créer le dossier build si nécessaire
$(BUILDDIR):
	mkdir -p $(BUILDDIR)

# Lien des objets pour créer l'exécutable dans le dossier build
$(BUILDDIR)/$(TARGET): $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

# Compilation des fichiers sources en fichiers objets dans le dossier build
$(BUILDDIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Nettoyage des fichiers objets, de l'exécutable, et du dossier build
clean:
	rm -rf $(BUILDDIR)

# Exécuter le programme depuis le dossier build
run: $(BUILDDIR)/$(TARGET)
	./$(BUILDDIR)/$(TARGET)
